name: Python Unittest CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: 1.5.1
    - name: Set up Poetry Path
      run: echo "$HOME/.local/bin" >> $GITHUB_PATH
    - name: Install dependencies using Poetry
      run: poetry install
    - name: Run unittests
      run: poetry run python -m unittest discover -s tests